version: "3.7"

services:
  app:
    build: docker/dev/app
    volumes:
      - ./:/var/www:cached
    ports:
      - 8080:8080

  api:
    build: docker/dev/api
    volumes:
      - ./data:/var/www/data:cached
    ports:
      - 3000:3000
